# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: .      # URL of the scope directory (where the SAF is located)
onNotExist: warn # Action in case something doesn't exist
output: .        # (root) directory for output files to be written to

## Machine Readable Glossary Tool
mrgt:
  vsntag:        # versiontag of MRG to generate. Default: all MRGs
  macros: # macros to be used for formPhrases
    "{ss}": ["", "s", "'s", "(s)"]
    "{yies}": ["y", "y's", "ies"]

## Human Readable Glossary Tool
hrgt:
  interpreter: default           # `default` (default), or regex
  converter[1]: "## [{{#if glossaryTerm}}{{noRefs glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n\n{{#if glossaryText}}{{glossaryText}}{{else}}no `glossaryText` was specified for this entry.{{/if}}\n\n{{#if glossaryNotes}}### Notes\n\n{{#each glossaryNotes}}- {{this}}\n{{/each}}\n{{/if}}"
  converter[2]: markdown-abbr-section-2  # add HRG-entries for abbreviations (i.e. that have a non-empty `glossaryAbbr` field)
  input:                         # glob pattern for files to be processed
    - "tev2-glossary.md"
    - "tev2-glossaries-demo.md"

## Term Reference Resolution Tool
trrt:
  interpreter: default           # `default`, `alt`, or regex
  converter: html-hovertext-link # `markdown-link`, `html-link`, `html-hovertext-link`, `html-glossarytext-link`, mustache/handlebars template
  converter[error]: "{{showtext}}{{log 'TRRT error converter:' err.dir '/' err.file '@' err.line ':' err.pos '[' ref.showtext ']' level='warn'}}"
  input:                         # glob pattern for files to be processed
    - "**/*.md"