# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: .      # URL of the scope directory (where the SAF is located)
onNotExist: warn # Action in case something doesn't exist
output: .        # (root) directory for output files to be written to

## Machine Readable Glossary Tool
mrgt:
  vsntag:        # versiontag of MRG to generate. Default: all MRGs
  mappings:
  # If one or more macros are specified here below, only they will be used by the MRGT.
  # And in that case, all macros defined in the tools and/or in the SAF will be disregarded.
    formphrase-macros:
      "{ss}":   ["","s","'s","(s)"]      # "act{ss}" --> "act", "acts", "act's", "act(s)"
      "{ess}":  ["","es","'s","(es)"]    # "regex{es}" --> "regex", "regexes", "regex's", "regex(es"
      "{yies}": ["y","y's","ies"]        # "part{yies}" --> "party", "party's", "parties"
      "{ying}": ["y","ying","ies","ied"] # "identif{ying}" --> "identify", "identifying", "identifies", "identified"
      "{es}":   ["e","es","ed","ing"]    # "mangag{es}" --> "manage", "manages", "managed", "managing"
      "{able}": ["able","ability"]       # "cap{able}" --> "capable", "capability"

## Human Readable Glossary Tool
hrgt:
  mappings:
    # all interpreters/converters specified below are added to the set that the HRGT already has
    # if an interpreter/converter is predefined, or specified in the SAF, the specification below will override the predefined one.
    interpreters: # note that backslashes in regexes need to be properly escaped. Also use single/double quotes with care.
    converters: # note that you do not inadvertently mix single and double quotes.
      "html-with-notes":
        '## [{{#if glossaryTerm}}{{noRefs glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n\n{{#if glossaryText}}{{glossaryText}}{{else}}no `glossaryText` was specified for this entry.{{/if}}\n\n{{#if glossaryNotes}}### Notes\n\n{{#each glossaryNotes}}- {{this}}\n{{/each}}\n{{/if}}'
      "html-abbrs":
        '{{#if glossaryAbbr}}## [{{glossaryAbbr}}]({{localize navurl}})\n\nSee: [{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{termid}}@)\n\n{{else}}{{log level="silent"}}{{/if}}'
    sorters: # note that you do not inadvertently mix single and double quotes.
  # predefined interpreters is only `default` (and any one defined in the SAF)
  interpreter: default
  # predefined converters are `markdown-table-row`, `markdown-section-2`, `markdown-section-3` (and the ones defined in the SAF)
  converter[1]: html-with-notes
  converter[2]: html-abbrs
  # glob pattern for files to be processed
  input:                         
    - "tev2-glossary.md"
    - "tev2-glossaries-demo.md"

## Term Reference Resolution Tool
trrt:
  mappings:
    # all interpreters/converters specified below are added to the set that the TRRT already has
    # if an interpreter/converter is predefined, or specified in the SAF, the specification below will override the predefined one.
    interpreters: # note that backslashes in regexes need to be properly escaped. Also use single/double quotes with care.
      default: '(?:(?<=[^`\\\\])|^)\\[(?=[^@\\n\\]]+\\]\\([^@)]*@[:a-z0-9_-]*\\))(?<showtext>[^@\\n\\]]+)\\]\\((?:(?:(?<type>[a-z0-9_-]*):)?)(?:(?<term>[^@\\n:#)]*?)?(?:#(?<trait>[^@\\n:#)]*))?)?@(?<scopetag>[a-z0-9_-]*)(?::(?<vsntag>[a-z0-9_-]*))?\\)'
      alt: '(?:(?<=[^`\\\\])|^)\\[(?=[^@\\n\\]]+?@[:a-z0-9_-]*\\](?:\\([#:a-z0-9_-]+\\))?)(?<showtext>[^@\\n\\]]+?)@(?<scopetag>[a-z0-9_-]*)(?::(?<vsntag>[a-z0-9_-]*?))?\\](?:\\((?:(?:(?<type>[a-z0-9_-]+):)?)(?<term>[^@\\n:#)]*?)(?:#(?<trait>[^@\\n:#)]+?))?\\))?'
    converters: # note that you do not inadvertently mix single and double quotes.
      "remove-termref-and-log-error":
        "{{ref.showtext}}{{log 'TRRT error converter:' err.dir '/' err.file '@' err.line ':' err.pos '[' ref.showtext ']' level='warn'}}"
  # predefined interpreters are `default`, `alt` (and the ones defined in the SAF)
  interpreter: default
  # predefined converters are `markdown-link`, `html-link`, `html-hovertext-link`, `html-glossarytext-link` (and the ones defined in the SAF)
  converter: html-hovertext-link
  converter[error]: remove-termref-and-log-error
  # glob pattern for files to be processed
  input:
    - "**/*.md"